[project]
name = "crpssplots"
version = "0.1.0"
description = "Plot creation for CROSS model comparison"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crosscontract>=0.6.0",
    "dotenv>=0.9.9",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pathlib>=1.0.1",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
